name: '${name}'
main: '${group}.${name}'

authors: ${authors}

version: '${version}'
api-version: '${apiVersion}'
description: '${description}'
website: '${website}'

folia-supported: true

softdepend:
  - CMI
  - HolographicDisplays
  - DecentHolograms
  - PlaceholderAPI
  - MVdWPlaceholderAPI
  - Multiverse-Core
  - MultiWorld
  - MyWorlds
  - WorldEdit
  - WorldGuard
  - Oraxen
  - ItemsAdder

commands:
  crazyenvoys:
    description: "Manage your envoys however you want."
    aliases:
      - envoys
      - envoy

permissions:
  crazyenvoys.admin:
    default: op